// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApug6kkkkeaBirUdtHIAQT7xHp-bms3aE',
    appId: '1:960622474867:web:49cf35bb76e287d3a49c06',
    messagingSenderId: '960622474867',
    projectId: 'jamaathi-484c7',
    authDomain: 'jamaathi-484c7.firebaseapp.com',
    storageBucket: 'jamaathi-484c7.appspot.com',
    measurementId: 'G-D5XX7YEQTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMr0wYoaef-efbSW4yepP8KsrJYo5fJ68',
    appId: '1:960622474867:android:296f0d910292e4a3a49c06',
    messagingSenderId: '960622474867',
    projectId: 'jamaathi-484c7',
    storageBucket: 'jamaathi-484c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8IHLy4TVjkOl8iiyWrCs-JfrQwK-6fWs',
    appId: '1:960622474867:ios:b2a5158a1bcdd887a49c06',
    messagingSenderId: '960622474867',
    projectId: 'jamaathi-484c7',
    storageBucket: 'jamaathi-484c7.appspot.com',
    iosClientId: '960622474867-49pngk7l1dbjunuakqp7oi7a2rlag61s.apps.googleusercontent.com',
    iosBundleId: 'com.example.jamaathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8IHLy4TVjkOl8iiyWrCs-JfrQwK-6fWs',
    appId: '1:960622474867:ios:cfd0497e7c16769ea49c06',
    messagingSenderId: '960622474867',
    projectId: 'jamaathi-484c7',
    storageBucket: 'jamaathi-484c7.appspot.com',
    iosBundleId: 'com.example.jamaathi.RunnerTests',
  );
}
